In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.losses import MeanSquaredError
from sklearn.preprocessing import MinMaxScaler
import math

In [2]:
df = pd.read_csv("model.csv")

In [3]:
dataraw = df.values.astype('float32')
dataset = dataraw
dataset

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [4., 0., 0., ..., 0., 4., 0.],
       [0., 4., 0., ..., 4., 0., 4.],
       [0., 0., 4., ..., 0., 4., 0.]], dtype=float32)

In [4]:
TRAIN_SIZE = 1

train_size = int(len(dataset) * TRAIN_SIZE)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size, :], dataset[train_size:len(dataset),:]
print('Numero de observações (dados de treino, dados de teste): ' + str((len(train),len(test))))

Numero de observações (dados de treino, dados de teste): (176, 0)


In [5]:

y = dataset[:,0]
X = dataset[:,1:]
print(X)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [0. 0. 4. ... 0. 4. 0.]
 [4. 0. 0. ... 4. 0. 4.]
 [0. 4. 0. ... 0. 4. 0.]]


In [6]:
train_y = np.array(y)
train = np.array(X)
train_X = np.reshape(train, (train.shape[0],1,train.shape[1]))
print(train_X.shape)

(176, 1, 8)


In [7]:
model = Sequential()

In [8]:
model.add(LSTM(250, input_shape = (1, 8)))

In [9]:
model.add(Dense(5))
model.add(Dense(4))

In [10]:

model.compile( optimizer='adam', loss="mean_absolute_error")

In [11]:
model.fit(train_X, train_y, epochs=1000, batch_size=20, verbose=1)

000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1936
Epoch 772/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1894
Epoch 773/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1899
Epoch 774/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1910
Epoch 775/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1924
Epoch 776/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1902
Epoch 777/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1898
Epoch 778/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1909
Epoch 779/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1871
Epoch 780/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1854
Epoch 781/1000
176/176 [==============================] - 0s 2ms/sample - loss: 0.1866
Epoch 782/1000
176/176 [==============================

In [12]:


dados = [[0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0]]
adados = np.array(dados)
ar = np.reshape(adados, (adados.shape[0],1,adados.shape[1]))

previsao = model.predict(ar)

print(previsao)

[[3.9971747 3.9787319 4.00673   3.9894931]]
